### ISSUE TITLE
Analytics: Ctrl-f does not search in ABI

### ISSUE THREAD

**Issue by zomglings** [moonstream-to/frontend#107]
I was on the Analytics screen and I wanted to see if an event was in the ABI.

So I typed `ctrl-f <event name>`. It didn't return any results.

When I manually scanned the ABI, I did find the event.

This tells me that ctrl-f search is not searching the text in the ABI field. This is a bad user experience.

**Comment by Anton-Mushnin** [comment]
search in result when it's present also would be good I think
